#region * * * P L E A S E   D O   N O T   M O D I F Y * * *
/***************************************************************************
** Module name   : Ntcruise.cs
** Description   : Server Stub File for .NET (10.8.0.0)
**
**                 * * *  P L E A S E   D O   N O T   M O D I F Y  * * *
**
** Author        : Generated by Software AG EntireX IDL Compiler
** Template      : csharp_server.tpl for C#
** Platform      : .NET-able Platforms
** Usage         : <use wizard>
***************************************************************************/
#endregion
#region parameters
/**************************************************************************
** sanitize C#
** Broker       : localhost:1971
** Service      : RPC/NATSRV2800/CALLNAT
** ATOSTRING       : Default
** A1TOCHAR        : false
** B1TOBYTE        : false
** TRIM            : false
** SANITIZE        : true
***************************************************************************/
#endregion
#region required namespaces
using System;
using System.Text;
using System.Runtime.InteropServices;
using SoftwareAG.EntireX.NETWrapper.Runtime;
#endregion

#region AssemblyInfo
#if USE_ASSEMBLY_INFO
using System.Reflection ;
[assembly: AssemblyTitle("EntireX .NET Wrapper Server")]
[assembly: AssemblyDescription("EntireX .NET Wrapper Server")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Software AG")]
[assembly: AssemblyProduct("EntireX Communicator")]
[assembly: AssemblyCopyright("")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: AssemblyVersion("1.0.*")]
[assembly: AssemblyDelaySign(false)]
[assembly: AssemblyKeyFile("")]
[assembly: AssemblyKeyName("")]
#endif
#endregion

namespace SoftwareAG.EntireX.NETWrapper.Server.NTCRUISE.Groups
{
#region Groups for LIBRARY 'NTCRUISE', PROGRAM 'FindCruise'

  public class Findcruise
  {
    public class NcParms
    {
      [SendAs(IdlType.N, preDecimal=8, postDecimal=0, Id=0)]public decimal crId;
      [SendAs(IdlType.A, Length=13f, Id=1, Trim=false)]public StringBuilder crEd ;
      [SendAs(IdlType.A, Length=7f, Id=2, Trim=false)]public StringBuilder crEt ;
      [SendAs(IdlType.A, Length=20f, Id=3, Trim=false)]public StringBuilder crFromh ;
      [SendAs(IdlType.A, Length=20f, Id=4, Trim=false)]public StringBuilder crP1w ;
      [SendAs(IdlType.A, Length=20f, Id=5, Trim=false)]public StringBuilder crP2w ;
      [SendAs(IdlType.A, Length=20f, Id=6, Trim=false)]public StringBuilder crP3w ;
      [SendAs(IdlType.A, Length=13f, Id=7, Trim=false)]public StringBuilder crSd ;
      [SendAs(IdlType.A, Length=7f, Id=8, Trim=false)]public StringBuilder crSt ;
    }
  }

#endregion
#region Groups for LIBRARY 'NTCRUISE', PROGRAM 'ListCruise'

  public class Listcruise
  {
    public class NcParms
    {
      [SendAs(IdlType.N, preDecimal=8, postDecimal=0, Id=0)]public decimal crId;
      [SendAs(IdlType.A, Length=13f, Id=1, Trim=false)]public StringBuilder crEd ;
      [SendAs(IdlType.A, Length=7f, Id=2, Trim=false)]public StringBuilder crEt ;
      [SendAs(IdlType.A, Length=20f, Id=3, Trim=false)]public StringBuilder crP2w ;
      [SendAs(IdlType.A, Length=20f, Id=4, Trim=false)]public StringBuilder crP3w ;
      [SendAs(IdlType.A, Length=13f, Id=5, Trim=false)]public StringBuilder crSd ;
      [SendAs(IdlType.A, Length=7f, Id=6, Trim=false)]public StringBuilder crSt ;
      [SendAs(IdlType.A, Length=20f, Id=7, Trim=false)]public StringBuilder crStatus ;
      [SendAs(IdlType.A, Length=20f, Id=8, Trim=false)]public StringBuilder crToh ;
      [SendAs(IdlType.A, Length=20f, Id=9, Trim=false)]public StringBuilder crYachtName ;
    }
  }

#endregion
}
namespace SoftwareAG.EntireX.NETWrapper.Server.NTCRUISE
{
  [EntireXVersion("10.8.0.0")]
  [Library("NTCRUISE")]
  public class Ntcruise
  {
#region Method/Function for LIBRARY 'NTCRUISE' PROGRAM 'FindCruise'

    [Program("FindCruise")]
    public void Findcruise(
      [SendAs(IdlType.Group)][In, Out] ref SoftwareAG.EntireX.NETWrapper.Server.NTCRUISE.Groups.Findcruise.NcParms ncParms
    ){
      // Write your own code here

    }

#endregion
#region Method/Function for LIBRARY 'NTCRUISE' PROGRAM 'ListCruise'

    [Program("ListCruise")]
    public void Listcruise(
      [SendAs(IdlType.Group)][In, Out] ref SoftwareAG.EntireX.NETWrapper.Server.NTCRUISE.Groups.Listcruise.NcParms ncParms
    ){
      // Write your own code here

    }

#endregion
  }
}

